### ISSUE TITLE
Trying to convert an image

### ISSUE THREAD

**Issue by philiptolk** [FLIF-hub/UGUI_FLIF#3]
npm start

> ugui_flif@0.3.5 start /Users/user/UGUI_FLIF
> nw .

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[29302:0211/221744:INFO:CONSOLE(2728)] ""%cCould not read settings file from location:" "font-family: sans-serif"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (2728)
[29302:0211/221744:INFO:CONSOLE(2729)] ""%c\"/Users/user/Library/Application Support/ugui_flif/uguisettings.json\"" "background: #EEEEF6;border: 1px solid #B2B0C1;border-radius: 7px;padding: 2px 8px 3px;color: #5F5F5F;line-height: 22px;box-shadow: 0px 0px 1px 1px rgba(178,176,193,0.3)"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (2729)
[29302:0211/221744:INFO:CONSOLE(2730)] ""%cError:" "font-family: sans-serif;font-weight: bold"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (2730)
[29302:0211/221744:INFO:CONSOLE(2731)] ""%cENOENT: no such file or directory, open '/Users/user/Library/Application Support/ugui_flif/uguisettings.json'" "background: #F6EEEE;border: 1px solid #C1B0B2;border-radius: 7px;padding: 2px 8px 3px;color: #5F5F5F;line-height: 22px;box-shadow: 0px 0px 1px 1px rgba(193,176,178,0.3)"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (2731)
[29302:0211/221805:INFO:CONSOLE(363)] ""executables/osx/flif --repeats=3 \"/Users/user/Images/Free/image.png\" \"/Users/user/Images/Free/image.flif\""", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (363)
[29302:0211/221805:INFO:CONSOLE(364)] ""stdout: "", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (364)
[29302:0211/221805:INFO:CONSOLE(365)] ""stderr: /bin/sh: executables/osx/flif: Permission denied\n"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (365)
[29302:0211/221805:INFO:CONSOLE(367)] ""Executable Error: Error: Command failed: /bin/sh -c executables/osx/flif --repeats=3 \"/Users/user/Images/Free/image.png\" \"/Users/user/Images/Free/image.flif\"\n/bin/sh: executables/osx/flif: Permission denied\n"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (367)
[29302:0211/221805:INFO:CONSOLE(371)] ""---------------------"", source: file:///Users/user/UGUI_FLIF/_scripts/ugui.js (371)
[29302:0211/221805:INFO:CONSOLE(229)] ""Executable has closed with the exit code: 126"", source: file:///Users/user/UGUI_FLIF/_scripts/app.js (229)
[29302:0211/221808:ERROR:nw_shell.cc(336)] Error: ENOENT: no such file or directory, stat '/Users/user/Images/Free/image.flif'
    at Error (native)
    at Object.fs.statSync (fs.js:839:18)
    at updateUI (file:///Users/user/UGUI_FLIF/_scripts/app.js:194:39)
[29302:0211/221808:INFO:CONSOLE(839)] "Uncaught Error: ENOENT: no such file or directory, stat '/Users/user/Images/Free/image.flif'", source: fs.js (839)

**Comment by TheJaredWilcurt** [comment]
@pmtolk 

Are you trying to run this repo locally to work on it? In which case:

* https://github.com/FLIF-hub/UGUI_FLIF#contributing

otherwise, if you just want to run the application you can download the version from your OS here:

* https://github.com/FLIF-hub/UGUI_FLIF/releases
* or here:
* http://flif.info/UGUI_FLIF/

**Important Note:** UGUI: FLIF is pretty out of date (October 2015). I should hopefully have some time soon to update it to use FLIF v0.2 (the finished FLIF standard).

So the `.flif` files produced by this may look wrong when decoded with the newer standard since there have been breaking changes in the bitstream since UGUI: FLIF's last release.

**Comment by philiptolk** [comment]
Thanks, I downloaded the mac app from the release link 
https://github.com/FLIF-hub/UGUI_FLIF/releases
and it worked to convert a 3.2 meg png to a 658k flif file.

**Comment by TheJaredWilcurt** [comment]
@pmtolk 

I just finished doing the builds for FLIF v0.2.2 (stable/latest). So I should be able to start working on this again soon. For the time being you can download the latest build and replace the executable in UGUI: FLIF v0.3.5 with it, and modify one line of code to allow the new executable to run. This will allow you to produce modern FLIF files that will work in the future with all decoders.

Right-Click on `UGUI_FLIF.app` and open it's contents.

Edit this file in a text editor:

* `UGUI_FLIF.app\Contents\Resources\app.nw\_scripts\app.js`

on `line 183` change it to this line:

```js
var executableAndArguments = flif + ' -e -N -Q100 -E100 "' + fullPath + '" "' + inputFlif + '"';
```

Then replace this file with the latest build:

* `UGUI_FLIF.app\Contents\Resources\app.nw\executables\osx\flif`

You can get the built FLIF binary from here (osx64-flif_0.2.2.zip).

* https://github.com/FLIF-hub/FLIF/releases/tag/v0.2.2

It should be uploaded later today, if you are seeing this before that happens you use this mirror:

* https://dl.dropboxusercontent.com/u/1050916/temp/flif_0.2.2/osx64-flif_0.2.2.zip
